import styles from "../css/terms.module.css";
import langData from "../system/lang.json"
import { useLang } from "../context/LangContext";

export default function Terms({ setTerms }) {

  // 언어 변경 함수 전역 콘텍스트
  const { lang, toggleLang } = useLang();

  return (
    <div className={styles.back}>
      <div className={styles.termsWrapper}>
        <div className={styles.closeIcon} onClick={()=>{setTerms(false)}}>
          <img src='/close.png' height="24px"/>
        </div>
        <div style={{marginBottom:"20px"}}>
          <div className={styles.policyText}>
            {lang == "en" ? langData.policy[0] : langData.policy[1]}
          </div>
          <div className={styles.termsDate}>
            {lang == "en" ? "Last Updated on 2025.09.25" : "마지막 업데이트 2025.09.25"}
          </div>
        </div>
        <div className={styles.termsContentWrapper}>
          <span className='medium'>Summary (Non-Binding)</span>
          <p className='grayText line-20'>This Terms of Use document explains the rules governing your use of the Classrules.org website and services. By using our services, you agree to be bound by these Terms, which cover permitted use, intellectual property, disclaimers, limitations of liability, and applicable Korean law. Please read carefully.</p>
          <span className='medium'>Contact Information:</span>
          <div className='flex grayText' style={{margin:"10px 0 20px 0", gap:'4px', flexDirection:"column"}}>
            <div>Classrules.org</div>
            <div>[Full Address in Korea]</div>
            <div>Email: [contact@example.com]</div>
          </div>
          <div className={styles.bigTitle}>Acceptance of Terms</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Binding Agreement.</span> By accessing, browsing, or using the Classrules.org website (“Site”) and related services (“Services”), you agree to comply with and be legally bound by these Terms of Use (“Terms”). If you do not agree, you must not use the Site or Services.</p>
            <p><span className={styles.mediumBlack}>Entity vs. Individual.</span> If you are using the Services on behalf of a company, organization, or other legal entity, you represent and warrant that you are authorized to bind that entity to these Terms. In such cases, “you” or “User” shall mean both you as an individual and the entity you represent.</p>
            <p><span className={styles.mediumBlack}>Eligibility.</span> You affirm that you are at least the age of majority under Korean law (19 years) and have the legal capacity to enter into this Agreement.
            Updates to Terms. We may modify these Terms from time to time. The updated Terms will take effect upon posting on the Site with the revised “Last Updated” date. Your continued use of the Services after such posting constitutes acceptance of the updated Terms.</p>
            <p><span className={styles.mediumBlack}>Jurisdiction.</span> These Terms shall be governed by and construed in accordance with the laws of the Republic of Korea, without regard to conflict of law principles. Any disputes arising hereunder shall be subject to the exclusive jurisdiction of the competent courts of Seoul, Republic of Korea.</p>
          </div>
          <div className={styles.bigTitle}>Definitions</div>
          <p className='grayText'>For purposes of these Terms:</p>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li><span>“Services”</span> means all online services, content, and functionality provided by Classrules.org, including but not limited to the terminology accuracy evaluation, information resources, and user support features.</li>
            <li><span>“Site”</span> means the website and associated domains operated by Classrules.org within the Republic of Korea.</li>
            <li><span>“User”</span> means any individual or legal entity that accesses or uses the Services, with or without registration.</li>
            <li><span>“Account”</span> means a registered user profile created by providing required information to access certain Services.</li>
            <li><span>“User Content”</span> means any terms, text, data, or materials submitted by a User to the Services.</li>
            <li><span>“Outputs”</span> means any responses, explanations, or informational results generated by the Services in response to User Content.</li>
            <li><span>“Terminology Accuracy Service”</span> (also referred to as the “STE Checker”) means the system functionality that evaluates User-submitted terms or text for accuracy, clarity, and appropriateness in the context of ship classification, shipbuilding, or maritime technical domains, including alignment with ASD-STE100 Simplified Technical English rules.</li>
            <li><span>“Professional Advice”</span> means engineering, legal, or classification society approval. The Services expressly do not provide Professional Advice.</li>
            <li><span>“IACS Members”</span> means the International Association of Classification Societies and its member organizations (e.g., ABS, BV, ClassNK, DNV, KR, LR). Classrules.org is not affiliated with IACS or any of its members.</li>
            <li><span>“Classification Approval”</span> means official review, endorsement, or certification by a recognized classification society. The Services do not provide Classification Approval.</li>
            <li><span>“Third-Party Materials”</span> means any external content, software, or resources accessed through links or integrations.</li>
            <li><span>“Feedback”</span> means comments, suggestions, or reports voluntarily provided by Users regarding the Services.</li>
            <li><span>“STE/ASD-STE100”</span> means the international controlled language specification Simplified Technical English, developed and maintained by the AeroSpace and Defence Industries Association of Europe (ASD) through its STE Maintenance Group (STEMG). Classrules.org references ASD-STE100 for informational purposes only and does not claim ownership, endorsement, or certification by ASD.</li>
          </ul>
          <div className={styles.bigTitle}>About the Services</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>General Information.</span> The Services provide Users with access to informational resources concerning ship classification, shipbuilding, maritime technical standards, and related regulatory or industry domains. Content is curated to assist Users in understanding terminology, conventions, and practices relevant to the maritime sector.</p>
            <p><span className={styles.mediumBlack}>Terminology Accuracy Service (STE Checker). </span> The Services include a functionality that allows Users to submit individual terms, phrases, or short texts for evaluation. The system processes these inputs and generates informational outputs regarding:</p>
          </div>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li>The relevance and accuracy of such terms within the ship classification and shipbuilding industries.</li>
            <li>The clarity and appropriateness of the terms for use in technical and contractual documents.</li>
            <li>Heuristic conformity checks against the principles of Simplified Technical English (STE/ASD-STE100), including rules and controlled dictionary guidelines.</li>
          </ul>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Scope and Limitations.</span> The outputs of the Terminology Accuracy Service are intended solely for informational and educational purposes. The system is designed to provide guidance and signals concerning usage, clarity, and conformity, but:</p>
          </div>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li>The outputs do not constitute authoritative approval, legal advice, engineering judgment, or official rule interpretation.</li>
            <li>The outputs do not replace formal classification rules, statutory regulations, or professional expertise.</li>
            <li>Users remain responsible for validating terminology and ensuring compliance with applicable laws, regulations, and class society requirements.</li>
          </ul>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>No Classification, Engineering, or Legal Approval.</span> The Services are not a substitute for classification approval, plan approval, technical consultancy, or legal review. The International Association of Classification Societies (IACS) and its member societies establish and coordinate minimum technical requirements for safer and cleaner shipping. Classrules.org is not a classification society and does not issue classification, engineering, or legal approvals of any kind.</p>
          </div>
          <div className={styles.bigTitle}>No Affiliation; Industry Disclaimers</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Non-Affiliation with IACS and Class Societies.</span> Classrules.org is an independent service provider. We are not affiliated with, endorsed by, or acting on behalf of the International Association of Classification Societies (IACS) or any of its member societies, including but not limited to ABS, Bureau Veritas (BV), ClassNK, DNV, Korean Register (KR), and Lloyd’s Register (LR). References to these organizations or their rules are provided strictly for identification and educational purposes only.</p>
            <p><span className={styles.mediumBlack}>STE Disclaimer.</span> Simplified Technical English (ASD-STE100) is a controlled language specification developed and maintained by the AeroSpace and Defence Industries Association of Europe (ASD) through its STE Maintenance Group (STEMG). Classrules.org references ASD-STE100 as a benchmark for terminology evaluation. We do not claim ownership of ASD-STE100, nor do we provide official endorsement, approval, or certification from ASD, STEMG, or any related body. Users are advised to consult the official ASD-STE100 specification for authoritative guidance.</p>
          </div>
          <div className={styles.bigTitle}>Account Registration & Eligibility</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Accurate Information.</span> To access certain features of the Services, Users may be required to create an account (“Account”). You agree to provide true, accurate, current, and complete information during the registration process, including but not limited to your name, email address, organization, and role.</p>
            <p><span className={styles.mediumBlack}>Security of Credentials.</span> You are responsible for maintaining the confidentiality of your Account credentials, including your password. You must promptly notify Classrules.org of any unauthorized use of your Account or any other breach of security.</p>
            <p><span className={styles.mediumBlack}>Responsibility for Use.</span> You are fully responsible for all activities that occur under your Account, whether performed by you or by a third party using your credentials.</p>
            <p><span className={styles.mediumBlack}>Account Types. </span>Classrules.org may offer different types of Accounts, such as individual accounts and enterprise accounts, each subject to specific terms or subscription conditions.</p>
            <p><span className={styles.mediumBlack}>Suspension and Termination.</span> Classrules.org reserves the right to suspend or terminate any Account, without liability, if:</p>
          </div>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li>false, misleading, or incomplete information is provided;</li>
            <li>the Account is used in violation of these Terms; or</li>
            <li>activity is detected that may compromise the security, integrity, or lawful use of the Services.</li>
          </ul>
          <div className={styles.bigTitle}>Permitted Use & License to Use the Site</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Grant of License.</span> Subject to your compliance with these Terms, Classrules.org grants you a limited, revocable, non-exclusive, non-transferable license to access and use the Services for internal, non-commercial purposes or for subscribed business use as expressly permitted under an enterprise agreement.</p>
            <p><span className={styles.mediumBlack}>Restrictions.</span> Except as expressly permitted, you may not:</p>
          </div>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li>resell, sublicense, or distribute the Services or Outputs;</li>
            <li>copy, reproduce, or bulk download content from the Site;</li>
            <li>reverse-engineer, decompile, or modify the Services;</li>
            <li>use the Services for automated or high-volume queries that interfere with the intended operation.</li>
          </ul>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Downloads.</span> Where the Site permits downloading of non-confidential materials (e.g., guidelines, summaries, or white papers), you may download a single copy solely for internal reference, provided you retain all copyright and proprietary notices.</p>
          </div>
          <div className={styles.bigTitle}>User Content (Submitted Terms, Text, Files)</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Ownership.</span> You retain all rights in and to any content, terms, text, or files that you submit to the Services (“User Content”).</p>
            <p><span className={styles.mediumBlack}>License Grant.</span> By submitting User Content, you grant Classrules.org a worldwide, non-exclusive, royalty-free license to host, store, process, analyze, and display such content solely for the purpose of providing and improving the Services, including evaluation of system performance, model training, and quality assurance.</p>
            <p><span className={styles.mediumBlack}>Warranties.</span> You represent and warrant that you have the necessary rights, licenses, and permissions to submit User Content and to grant the rights described in this section, and that your User Content does not infringe or violate any third-party rights.</p>
            <p><span className={styles.mediumBlack}>Removal.</span> Classrules.org reserves the right, but not the obligation, to remove User Content that is unlawful, offensive, or in violation of these Terms.</p>
          </div>
          <div className={styles.bigTitle}>Outputs & Feedback</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Outputs.</span> The Services may generate responses, explanations, conformity signals, or other analytical results (“Outputs”). Subject to your compliance with these Terms, you are granted a non-exclusive, non-transferable license to use the Outputs internally for informational and educational purposes.</p>
            <p><span className={styles.mediumBlack}>Underlying Rights.</span> Classrules.org and its licensors retain all rights, title, and interest in and to the underlying models, software, and methodologies used to generate Outputs. No ownership rights are transferred to you.</p>
            <p><span className={styles.mediumBlack}>Feedback. </span> You may, but are not required to, provide comments, suggestions, or reports regarding the Services (“Feedback”). By submitting Feedback, you grant Classrules.org a perpetual, irrevocable, royalty-free license to use, reproduce, modify, and implement such Feedback for any purpose, without obligation of attribution or compensation.</p>
          </div>
          <div className={styles.bigTitle}>STE-Related Terms (ASD-STE100)</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Heuristic Evaluation.</span> The Terminology Accuracy Service (STE Checker) is designed to provide heuristic evaluations of User Content against certain rules and principles of Simplified Technical English (ASD-STE100), including dictionary-based checks. Outputs are intended as signals or indications only, and do not constitute certification or approval.</p>
            <p><span className={styles.mediumBlack}>No Certification.</span> Classrules.org does not and cannot provide formal certification of STE compliance. Users seeking official conformance must consult the authoritative ASD-STE100 specification and, if applicable, seek review from qualified professionals.</p>
            <p><span className={styles.mediumBlack}>Ownership of STE. ASD-STE100.</span> is a copyrighted and trademarked specification owned by the AeroSpace and Defence Industries Association of Europe (ASD) and maintained by the STE Maintenance Group (STEMG). All references made by Classrules.org are under fair informational use</p>
            <p><span className={styles.mediumBlack}>OUser Responsibility. </span> Users remain responsible for ensuring that their documents, manuals, or submissions conform to applicable standards and regulations. Outputs generated by the STE Checker are supplemental aids and should not replace consultation of the official ASD-STE100 Issue (currently Issue 9) or other governing documentation.</p>
          </div>
          <div className={styles.bigTitle}>Professional / Classification / Legal Non-Advice</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Informational Nature of Services.</span> The Services, including but not limited to terminology evaluations, clarity judgments, and STE conformance signals, are intended to provide general informational support to Users. They are designed to assist with understanding and interpreting maritime terminology and best practices, but they are not professional services.
            The content generated is not tailored to the specific circumstances of any ship, project, contract, or regulatory compliance matter.
            </p>
            <p><span className={styles.mediumBlack}>Exclusion of Approval or Certification.</span> Classrules.org does not issue any form of “approval,” “endorsement,” or “certification” with respect to shipbuilding terms, technical documents, or compliance with maritime standards. Such approvals remain within the sole authority of recognized classification societies and relevant regulatory bodies. Users are strongly advised to consult qualified professionals and official institutions before making decisions or taking actions that rely on technical or legal standards.
            </p>
          </div>
          <div className={styles.bigTitle}>Third-Party Sources, Links, and Materials</div>
          <div className='grayText'>
            <p>
              <span className={styles.mediumBlack}>External Links.</span> The Site may provide links to third-party websites, resources, or materials. 
              These links are included solely for the convenience of Users and to provide additional informational pathways.
            </p>
            <p>
              <span className={styles.mediumBlack}>No Endorsement or Control.</span> The inclusion of any link does not imply that Classrules.org 
              endorses, recommends, or has control over the linked websites, their operators, or their content. 
              Classrules.org expressly disclaims responsibility for the accuracy, legality, or appropriateness of third-party materials.
            </p>
            <p>
              <span className={styles.mediumBlack}>Compliance with Third-Party Terms.</span> Users who choose to access third-party websites 
              through the Site do so entirely at their own risk and are subject to the terms and conditions, privacy policies, 
              and intellectual property notices of those third-party websites.
            </p>
            <p>
              <span className={styles.mediumBlack}>Respect for Intellectual Property.</span> Any trademarks, service marks, copyrights, 
              or proprietary rights associated with third-party materials remain the property of their respective owners. 
              Users must respect these rights and may not use third-party content in ways that violate the rights of others or applicable law.
            </p>
          </div>
          <div className={styles.bigTitle}>Accuracy, Availability, and Change Control</div>
          <div className='grayText'>
            <p>
              <span className={styles.mediumBlack}>“As Is” Basis.</span> The Services and all related content are provided strictly on an “AS IS” 
              and “AS AVAILABLE” basis. Classrules.org makes no representations or warranties about the completeness, correctness, reliability, 
              or suitability of any Outputs, terminology evaluations, or supporting content.
            </p>
            <p>
              <span className={styles.mediumBlack}>No Guarantee of Performance.</span> While Classrules.org strives to provide reliable and updated 
              information, it cannot guarantee that the Services will always be error-free, uninterrupted, or free of inaccuracies. 
              Models, heuristics, and content sources may contain errors or omissions.
            </p>
            <p>
              <span className={styles.mediumBlack}>Evolving Systems.</span> The Services are built upon AI-driven systems, data models, and rule-based 
              evaluations that are constantly evolving. As a result, Outputs may vary over time, and previously generated results may not remain 
              consistent or accurate in future versions.
            </p>
            <p>
              <span className={styles.mediumBlack}>Right to Modify or Suspend.</span> Classrules.org reserves the right to modify, suspend, or 
              discontinue any aspect of the Services, including features, tools, or content, at any time without prior notice. Such changes may 
              occur due to technical updates, regulatory requirements, or business decisions, and Classrules.org shall not be liable for any 
              consequences of such modifications.
            </p>
          </div>
          <div className={styles.bigTitle}>AI / Automation-Specific Disclosures</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Probabilistic Nature of Outputs.</span> The Outputs generated by the Services are the result of probabilistic models, heuristic checks, and automated systems. These outputs may contain errors, omissions, or outdated information, particularly where rules evolve or external standards are updated.</p>
            <p><span className={styles.mediumBlack}>Verification Requirement.</span> Users are solely responsible for verifying the accuracy and applicability of Outputs against official rule sets, class society publications, and regulatory documents before relying on them for decision-making.</p>
            <p><span className={styles.mediumBlack}>No Sole Basis for Decisions.</span> Outputs must not be used as the sole basis for ship design, compliance planning, contractual drafting, or safety-related decisions. They are aids to human judgment and not replacements for professional expertise, technical review, or regulatory approval.</p>
            <p><span className={styles.mediumBlack}>Disclaimer of Liability.</span> Classrules.org disclaims all liability for errors, reliance, or damages arising from the use of Outputs without proper validation against authoritative sources.</p>
          </div>

          <div className={styles.bigTitle}>Prohibited Conduct</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>General Prohibitions.</span> Users agree not to misuse the Site or Services. Prohibited activities include, but are not limited to:</p>
          </div>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li>Data Scraping and Crawling: Attempting to harvest data or extract content through scraping, crawling, or automated means not expressly permitted.</li>
            <li>Denial-of-Service Attacks: Engaging in DDoS attacks or other activities that impair or overload the Services.</li>
            <li>Reverse Engineering: Attempting to decompile, disassemble, or reverse engineer any part of the Site, software, or models.</li>
            <li>Bypassing Security Controls: Circumventing authentication, encryption, or access-control mechanisms in place.</li>
            <li>Malware and Harmful Code: Uploading or transmitting viruses, worms, trojans, or other malicious software.</li>
            <li>Rights Violations: Using the Services to infringe on intellectual property rights, privacy rights, or other legal protections of third parties.</li>
            <li>Automated Bulk Queries: Conducting automated, high-volume queries or mirroring the Site in ways that disrupt or degrade service quality.</li>
            <li>Misleading Claims: Using the Services to generate or promote false or misleading statements suggesting classification approval, legal certification, or official endorsement.</li>
          </ul>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Enforcement.</span> Violation of these prohibitions may result in immediate suspension or termination of your Account, legal action, and reporting to competent authorities in the Republic of Korea.</p>
          </div>

          <div className={styles.bigTitle}>Intellectual Property</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Ownership.</span> The Site, Services, underlying models, software, and all related content are the intellectual property of Classrules.org or its licensors. All rights not expressly granted herein are reserved.</p>
            <p><span className={styles.mediumBlack}>No Implied License.</span> Nothing in these Terms grants Users any implied license to use trademarks, service marks, trade names, or copyrighted materials of Classrules.org, its licensors, or any third party.</p>
            <p><span className={styles.mediumBlack}>ASD-STE100 References.</span> References to ASD-STE100 Simplified Technical English are made strictly under fair informational use. Ownership of ASD-STE100 remains with the AeroSpace and Defence Industries Association of Europe (ASD). Classrules.org makes no claim of endorsement, affiliation, or certification by ASD or the STE Maintenance Group (STEMG).</p>
            <p><span className={styles.mediumBlack}>Reservation of Rights.</span> Except for the limited license to use the Services under these Terms, no rights, title, or interest are transferred to the User.</p>
          </div>

          <div className={styles.bigTitle}>Confidentiality (Enterprise Users)</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Confidential Submissions.</span> Enterprise Users may upload documents or data deemed confidential. Such submissions will be handled in accordance with a separate written agreement, which may include a Non-Disclosure Agreement (NDA), Data Processing Agreement (DPA), or Master Services Agreement (MSA).</p>
            <p><span className={styles.mediumBlack}>No Assumption Without Agreement.</span> Unless a separate agreement is signed, Classrules.org does not assume obligations of confidentiality for content uploaded through the general Site or Services. Users are advised not to upload sensitive or confidential information without an appropriate contractual framework in place.</p>
          </div>

          <div className={styles.bigTitle}>Privacy; Data Protection</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Privacy Policy Reference.</span> The processing of personal data through the Site and Services is governed by the Classrules.org Privacy Policy, which forms an integral part of these Terms.</p>
            <p><span className={styles.mediumBlack}>Categories of Data.</span> Personal data processed may include, without limitation, name, email address, organization, role, login credentials, IP address, and usage logs. For enterprise accounts, additional organizational identifiers may also be collected.</p>
            <p><span className={styles.mediumBlack}>Legal Bases.</span> Data is processed in compliance with the Personal Information Protection Act (PIPA) of the Republic of Korea and other applicable regulations, based on legal bases such as consent, contractual necessity, and legitimate interests.</p>
            <p><span className={styles.mediumBlack}>Retention.</span> Personal data is retained only for as long as necessary to fulfill the purposes of processing, comply with legal obligations, or resolve disputes. Data no longer required is securely deleted or anonymized.</p>
            <p><span className={styles.mediumBlack}>User Rights.</span> Under Korean law, Users have the right to access, correct, delete, or restrict the processing of their personal data, as well as the right to withdraw consent where applicable.</p>
            <p><span className={styles.mediumBlack}>Security Measures.</span> Classrules.org implements appropriate technical and organizational security measures to protect personal data against unauthorized access, alteration, disclosure, or destruction. However, no system is fully secure, and Classrules.org disclaims liability for breaches beyond its reasonable control.</p>
          </div>

          <div className={styles.bigTitle}>Export Controls & Sanctions</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Compliance.</span> The Services are subject to applicable export control laws and sanctions regulations, including those of the Republic of Korea and other jurisdictions where Users access the Services.</p>
            <p><span className={styles.mediumBlack}>User Representation.</span> By using the Services, you represent and warrant that you:</p>
          </div>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li>are not located in, under the control of, or a national or resident of any country or region subject to comprehensive trade sanctions or embargoes;</li>
            <li>are not identified on any government list of prohibited or restricted parties (including those maintained by Korea, the United States, the European Union, or the United Nations).</li>
          </ul>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Restricted Data.</span> Users may not upload, transmit, or otherwise provide through the Services any technical data or information that is subject to specific export controls, without first obtaining all required authorizations.</p>
          </div>

          <div className={styles.bigTitle}>Payment Terms (if Paid Tiers Apply)</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Fees.</span> Certain Services may be provided for a fee. All fees are payable in the currency specified at the time of purchase and are exclusive of applicable taxes, duties, or levies, which are your responsibility.</p>
            <p><span className={styles.mediumBlack}>Billing.</span> Payments will be billed according to the method and frequency selected (e.g., monthly, annually, per-user, or usage-based). By providing payment information, you authorize Classrules.org (or its payment processors) to charge you in accordance with the selected plan.</p>
            <p><span className={styles.mediumBlack}>Free Trials.</span> From time to time, Classrules.org may offer free trials or promotional subscriptions. At the end of any free-trial period, fees will apply unless you cancel before the trial expires.</p>
            <p><span className={styles.mediumBlack}>Refunds and Cancellations.</span> Except as required by Korean law or otherwise stated in an applicable subscription agreement, all fees are non-refundable, including fees paid in advance for partially used periods. Users may cancel subscriptions at any time, but cancellation will not entitle you to a refund.</p>
          </div>
          <div className={styles.bigTitle}>Open-Source & Third-Party Components</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Open-Source Software.</span> The Services may incorporate or provide access to third-party open-source software (“OSS”). Use of such OSS is subject to the applicable OSS license terms.</p>
            <p><span className={styles.mediumBlack}>License Precedence.</span> To the extent that any OSS license terms expressly override these Terms, the OSS license terms shall control only with respect to the relevant component.</p>
            <p><span className={styles.mediumBlack}>Notices.</span> Attribution and licensing notices for OSS and third-party components are made available within the Services or upon request.</p>
          </div>

          <div className={styles.bigTitle}>Indemnity</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>User Indemnity.</span> You agree to indemnify, defend, and hold harmless Classrules.org, its affiliates, officers, directors, employees, and agents from and against any and all claims, damages, liabilities, losses, costs, or expenses (including reasonable attorneys’ fees) arising out of or related to:</p>
          </div>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li>your User Content;</li>
            <li>your misuse of the Services;</li>
            <li>your violation of these Terms; or</li>
            <li>your infringement of any intellectual property, privacy, or other rights of a third party.</li>
          </ul>

          <div className={styles.bigTitle}>Disclaimers</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>General Disclaimer.</span> The Services and all related content are provided “AS IS” and “AS AVAILABLE”, without warranty of any kind.</p>
            <p><span className={styles.mediumBlack}>No Implied Warranties.</span> To the maximum extent permitted by law, Classrules.org disclaims all express, implied, or statutory warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, accuracy, reliability, or non-infringement.</p>
            <p><span className={styles.mediumBlack}>No Guarantee of Results.</span> Classrules.org makes no warranty that the Services will be error-free, uninterrupted, secure, or that the Outputs will meet your specific requirements or expectations.</p>
          </div>

          <div className={styles.bigTitle}>Limitation of Liability</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Limitation on Direct Damages.</span> To the fullest extent permitted by Korean law, Classrules.org’s total liability to you for any claim arising under or related to these Terms or the Services shall be limited to the greater of:</p>
          </div>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li>the amount you paid for the Services during the six (6) months preceding the claim, or</li>
            <li>KRW 1,000,000 (one million Korean Won).</li>
          </ul>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Exclusion of Certain Damages.</span> Classrules.org shall not be liable for any indirect, incidental, consequential, special, punitive, or exemplary damages, including but not limited to loss of profits, loss of data, or business interruption, even if advised of the possibility of such damages.</p>
            <p><span className={styles.mediumBlack}>Carve-Outs.</span> Nothing in these Terms shall limit or exclude liability for willful misconduct, gross negligence, death, or personal injury caused by Classrules.org, where such exclusion is prohibited under applicable law.</p>
          </div>

          <div className={styles.bigTitle}>Governing Law & Dispute Resolution</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Governing Law.</span> These Terms shall be governed by and construed in accordance with the laws of the Republic of Korea, without regard to conflict of law principles.</p>
            <p><span className={styles.mediumBlack}>Jurisdiction.</span> Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the competent courts in Seoul, Republic of Korea.</p>
            <p><span className={styles.mediumBlack}>Alternative Dispute Resolution.</span> Where appropriate, Classrules.org and the User may agree to resolve disputes through arbitration under the Korean Commercial Arbitration Board (KCAB) rules, provided both parties consent in writing.</p>
          </div>

          <div className={styles.bigTitle}>Changes to the Terms</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Right to Update.</span> Classrules.org reserves the right to update or modify these Terms at any time.</p>
            <p><span className={styles.mediumBlack}>Notice of Changes.</span> Material changes will be notified to Users via the Site, email, or other reasonable means.</p>
            <p><span className={styles.mediumBlack}>Effective Date.</span> Updated Terms take effect upon posting with a revised “Last Updated” date.</p>
            <p><span className={styles.mediumBlack}>Continued Use.</span> Your continued use of the Services after such posting constitutes acceptance of the updated Terms.</p>
          </div>

          <div className={styles.bigTitle}>Termination & Suspension</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Grounds for Termination.</span> Classrules.org may suspend or terminate your Account or access to the Services if you:</p>
          </div>
          <ul style={{lineHeight:'22px', color:'#555'}}>
            <li>violate these Terms;</li>
            <li>engage in fraudulent or unlawful activity;</li>
            <li>cause harm to the Services, other Users, or third parties; or</li>
            <li>fail to pay fees due (if applicable).</li>
          </ul>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Effect of Termination.</span> Upon termination, your right to use the Services will immediately cease. Sections relating to intellectual property, disclaimers, limitations of liability, indemnity, and governing law shall survive termination.</p>
          </div>

          <div className={styles.bigTitle}>Notices</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Electronic Communications.</span> You consent to receive notices and communications electronically. Notices may be provided via email, Site postings, or other reasonable means.</p>
            <p><span className={styles.mediumBlack}>Contact Information for Notices.</span> Notices to Classrules.org should be sent in writing to the address and email provided.</p>
            <p><span className={styles.mediumBlack}>Legal Service.</span> Service of process or formal legal notices must be delivered to the registered address of Classrules.org in Korea.</p>
          </div>

          <div className={styles.bigTitle}>Miscellaneous</div>
          <div className='grayText'>
            <p><span className={styles.mediumBlack}>Entire Agreement.</span> These Terms constitute the entire agreement between you and Classrules.org regarding use of the Services, superseding any prior agreements.</p>
            <p><span className={styles.mediumBlack}>Severability.</span> If any provision is found invalid or unenforceable, the remaining provisions shall remain in full force and effect.</p>
            <p><span className={styles.mediumBlack}>No Waiver.</span> Failure to enforce any right or provision shall not constitute a waiver of such right or provision.</p>
            <p><span className={styles.mediumBlack}>Assignment.</span> Users may not assign or transfer rights or obligations under these Terms without prior written consent from Classrules.org. Classrules.org may assign or transfer these Terms without restriction.</p>
            <p><span className={styles.mediumBlack}>Force Majeure.</span> Classrules.org shall not be liable for any failure or delay due to causes beyond its reasonable control, including but not limited to natural disasters, strikes, cyberattacks, or governmental actions.</p>
            <p><span className={styles.mediumBlack}>Interpretation.</span> Headings are for convenience only and do not affect interpretation. In case of discrepancies between language versions, the Korean version shall prevail.</p>
          </div>

        </div>
        <div className={styles.submitWrapper}>
          <button className={styles.makeBtn} onClick={()=>{setTerms(false)}}>{lang == "en" ? "Close" : "닫기"}</button>
        </div>

      </div>
      
    </div>
  )
}